name: CI

on: [pull_request]

jobs:
  test:
    name: Elixir ${{matrix.elixir}} OTP ${{matrix.otp}}

    runs-on: ubuntu-latest

    env:
      MIX_ENV: "test"
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}

    strategy:
      matrix:
        elixir: ["1.10.2"]
        include:
          - elixir: "1.10.2"
            otp: "22.3.2"

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Install dependencies
        run: mix deps.get

      - name: Compile application
        run: mix compile --warnings-as-errors

      - name: Analyze code
        run: mix format --check-formatted

      - name: Run tests
        run: mix test
