name: Elixir

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: 22.3.2
          elixir-version: 1.10.2

      - name: Install dependencies
        run: mix deps.get

      - name: Compile application
        run: mix compile --warnings-as-errors

      - name: Analyze code
        run: mix format --check-formatted

      - name: Run Tests
        run: mix test
